version: '3.9'

services:
  app:
    build: .
    container_name: financial-wallet-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/financial_wallet?schema=public'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: >
      sh -c "yarn prisma migrate deploy && yarn start"

  postgres:
    image: postgres:latest
    container_name: financial-wallet-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_wallet
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
